version: "3.0"
services:
  SingleNode:
    restart: always
    image: redis:7.2.4
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
    volumes:
      - ./data:/data
    command: redis-server --notify-keyspace-events KEA --save 60 1
