services:
  redis:
    restart: always
    image: redis:7.2.4
    environment:
      - DEBUG=false
    volumes:
      - ./data:/data
    command: redis-server --notify-keyspace-events KEA --save 60 1

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - 8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`frontend.localhost`) && PathPrefix(`/api`)
      - traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api
      - traefik.http.routers.backend.middlewares=backend-stripprefix@docker
    depends_on:
      - redis
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - 4173
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`frontend.localhost`)
      - traefik.http.routers.frontend.entrypoints=web
    depends_on:
      - backend
      - traefik

  traefik:
    image: traefik:v3.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro