version: "3.0"
services:
  redis:
    restart: always
    image: redis:7.2.4
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
    volumes:
      - ./data:/data
    command: redis-server --notify-keyspace-events KEA --save 60 1

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend